### ISSUE TITLE
Deobfuscate muni.js if you got approved by everyone.

### ISSUE THREAD

**Issue by doesDeveloper** [BotSolver/BetterMint#20]
Why obfuscate the muni.js then?
You said that people agreed to you for it, then why you obfuscated the script?
If its not intended for malicious purposes then why have you obfuscated the script?

**Comment by BotSolver** [comment]
what malicious purpose does ads give me, just close the ad, boom you supported me, and didn't get harmed.

if they are on github they would at least know what an ad is and that they aren't good to click so just close it.

it's obfuscated so people first of don't abuse my cpm key, and also just so people have a harder time removing it since they don't know if it's required or not, which it isn't, just a small change in the manifest and you're good lmfao.

![image](https://github.com/BotSolver/BetterMint/assets/73006302/713e3aff-12b5-4007-8dc2-5c26a17983fc)

as you can see people are fine with it, or already removed it.

**Comment by doesDeveloper** [comment]
I have already removed it in mine, but if you are going to put an advertisement script then don't obfuscate it. This is an opensource repo then why only obfuscate the ad script.
For your key security part, you are doing it wrong obfuscation does not help with securing your key.

**Comment by BotSolver** [comment]
I'll do as I please, don't like it? make something better or use something else.

I can obfuscate the whole project completely and turn the ads mandatory if I wanted. all with no issues.

If I wanted to actually "hide" anything, I wouldn't use an open source obfuscator when I have my own.

(also this isn't an open sourced repo if I don't want it to be, I can completely close and change the source if I pleased.
